### ISSUE TITLE
Document Viewer twice in Applications Menu

### ISSUE THREAD

**Issue by lfurtkevicova** [imincik/gis-lab#440] opened 2015-10-08 18:50 UTC
*Document Viewer* application belongs under these packs:
* Graphics
* Office

**Comment by imincik** [comment] 2015-10-09 09:57
I think it is not a bug, do you think so ?

**Comment by lfurtkevicova** [comment] 2015-10-09 10:09
I think so, I would say it is "enhancement" but I was not allowed to add label to issue ... I consider it useless to have it twice (but it is only my opinion)

**Comment by imincik** [comment] 2015-10-09 11:25
It is normal that on application can belong to multiple categories (at least according freedesktop spec [1]). Menu items are then constructed from these categories. Also, we take this configuration from upstream and it is not very good to change it. I am closing this issue.

1 - http://standards.freedesktop.org/desktop-entry-spec/latest/ar01s05.html

**Closed by imincik** 2015-10-09 11:25 UTC
Labels: + GIS.lab Desktop, bug
